meta:
  engine: 4.0.4
units:
points:
  zones:
    matrix:
      key:
        bind: $default_autobind
      anchor:
      columns:
        first:
          rows:
            first:
              column_net: C6
              row_net: R1
            second:
              column_net: C6
              row_net: R2
            third:
              column_net: C6
              row_net: R3
            forth:
              column_net: C6
              row_net: R4
        second:
          rows:
            first:
              column_net: C5
              row_net: R1
            second:
              column_net: C5
              row_net: R2
            third:
              column_net: C5
              row_net: R3
            forth:
              column_net: C5
              row_net: R4
        third:
          rows:
            first:
              column_net: C4
              row_net: R1
            second:
              column_net: C4
              row_net: R2
            third:
              column_net: C4
              row_net: R3
            forth:
              column_net: C4
              row_net: R4
        forth:
          rows:
            first:
              column_net: C3
              row_net: R1
              width: 75
              shift: [28.5,0]
            second:
              column_net: C3
              row_net: R2
              shift: [-28.5]
            third:
              column_net: C3
              row_net: R3
            forth:
              column_net: C3
              row_net: R4
        fifth:
          rows:
            first:
              column_net: C2
              row_net: R2
              shift: [0,19]
            second: 
              column_net: C2
              row_net: R3
            third:
              column_net: C2
              row_net: R4
        sixth:
          rows:
            first:
              column_net: C1
              row_net: R2
              shift: [0,19]
            second:
              column_net: C1
              row_net: R3
            third:
              column_net: C1
              row_net: R4
        seventh:
          rows:
            first:
              column_net: C2
              row_net: R1
              shift: [-19,-19]
            second:
              column_net: C1
              row_net: R1
              shift: [19, -19]    
  mirror: 150 
outlines:
  _keysOutline:
    - what: polygon
      points:
        - ref: matrix_first_first
          shift: [-10,-10]
        - ref: matrix_first_forth
          shift: [-10,10]
        - ref: matrix_sixth_third
          shift: [10,10]
        - ref: matrix_sixth_first
          shift: [10,-10]
        - ref: matrix_forth_first
          shift: [75/2+1, 8+1]
        - ref: matrix_seventh_second
          shift: [10,-10]
        - ref: matrix_seventh_first
          shift: [-10,-10]
        - ref: matrix_forth_first
          shift: [-0.5,-11]
      fillet: 2
  _keysOutline_mirror:
    - what: polygon
      points:
        - ref: mirror_matrix_first_first
          shift: [-10,-10]
        - ref: mirror_matrix_first_forth
          shift: [-10,10]
        - ref: mirror_matrix_sixth_third
          shift: [10,10]
        - ref: mirror_matrix_sixth_first
          shift: [10,-10]
        - ref: mirror_matrix_forth_first
          shift: [75/2+1, 8+1]
        - ref: mirror_matrix_seventh_second
          shift: [10,-10]
        - ref: mirror_matrix_seventh_first
          shift: [-10,-10]
        - ref: mirror_matrix_forth_first
          shift: [-0.5,-11]
      fillet: 2
  keysLayout:
    - what: rectangle
      size: 18
      where: true
      asym: source
  keysLayout_left:
    - what: outline
      name: keysLayout
    - what: outline
      name: _keysOutline_mirror
      operation: subtract
  keysLayout_right:
    - what: outline
      name: keysLayout
    - what: outline
      name: _keysOutline
      operation: subtract
  raw:
    - what: outline
      name: _keysOutline_mirror
    - what: outline
      name: _keysOutline
      operation: stack
  pcbOutline_left:
    - what: outline
      name: _keysOutline
      operation: stack
  pcbOutline_right:
    - what: outline
      name: _keysOutline_mirror
      operation: stack
pcbs:
  pcb_left:
    outlines:
      - outline : pcbOutline_left
    footprints:
      diodes:
        what: diode
        where: true
        params:
            from: "{{column_net}}"
            to: "{{row_net}}"
        adjust:
            shift: [0, -5]
            rotate: 180
      keyswitches:
        where: true
        asym: source
        what: mx
        params:
          reverse: false
          keycaps: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{row_net}}"
      mcu:
        what: ceoloide/mcu_nice_nano
        adjust:
          rotate: -90
        params:
            P2: C1
            P3: C2
            P4: C3 
            P5: C4
            P6: C5
            P7: C6
            
            P21: R1
            P20: R2
            P19: R3
            P18: R4
        where:
          ref: matrix_forth_first
          shift: [20.5,0]
  pcb_right:
    outlines:
      - outline : pcbOutline_right
    footprints:
      keyswitches:
        where: true
        what: mx
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{row_net}}"
      mcu:
        what: ceoloide/mcu_nice_nano
        adjust:
          rotate: -90
        params:
            P2: C1
            P3: C2
            P4: C3 
            P5: C4
            P6: C5
            P7: C6
            
            P21: R1
            P20: R2
            P19: R3
            P18: R4
        where:
          ref: mirror_matrix_forth_first
          shift: [20.5,0]
cases: